### ISSUE TITLE
RFE: Adding logon account to dependencies

### ISSUE THREAD

**Issue by mercierv** [aaearon/CyberArkPASDependentAccounts#2]
Hi everyone, 

Would it be possible, once we add a dependency account to a master account to link a logon account to this dependencies?
I'm mainly using Domain Service Account on which I setup Windows Service usage account. But as those account can't connect to the server, I need to link a logon account to it in order to rotate the password on the service. 

I will have to create at least 10 to 20 services a day, therefore having to do the link manually is a no-go for me. 
Is there already a way with your script, or is it already in your roadmap?

Cheers, 
V.

**Comment by aaearon** [comment]
You can do this with PoShPACLI:

```powershell
Add-PVFileCategory -safe $safeName -folder Root -file $fileName -category ExtraPass1Name -value $LogonAccountName
Add-PVFileCategory -safe $safeName -folder Root -file $fileName -category ExtraPass1Folder -value 'Root'
Add-PVFileCategory -safe $safeName -folder Root -file $fileName -category ExtraPass1Safe -value $LogonAccountSafe
```

**Comment by mercierv** [comment]
Thanks for the info, unfortunately (unless I don't know about it), this won't do the trick for me. 
As the script will be launch from the CPM, it means that I need a cred file on the CPM as well to launch the PoShPACLI right? and therefore the user in the cred file will be managed by CyberArk as well so whenever the password is rotated I will have to rotate the cred file as well. 

Or am I missing something and there is a way to launch PACLI from the CPM without cred file ?

Cheers, 
V

**Comment by aaearon** [comment]
See https://github.com/pspete/PoShPACLI#example-connecting-to-a-vault.

But I am a bit confused: why not add the logon account using `Add-PVFileCategory` right after the onboarding? It would be a part of the same process and you can run everything from the same script.

Something like
```powershell
Import-Module .\Add-PASDependentAccount.ps1

Add-PASDependentAccount `
        -MasterPassName "Operating System-ioSHARPWindowsDomainServiceAccount-iosharp.lab-serviceAccount01" `
        -SafeName Windows `
        -PlatformId INIFile `
        -address server01.iosharp.lab `
        -platformAccountProperties @{'FilePath' = 'C:\Example\example2.ini'; 'ConnectionType' = 'Windows File Sharing'; 'INISection' = 'Main'; 'INIParameterName' = 'Password'} `

Add-PVFileCategory -safe Windows -folder Root -file $fileName -category ExtraPass1Name -value $LogonAccountName
Add-PVFileCategory -safe Windows -folder Root -file $fileName -category ExtraPass1Folder -value 'Root'
Add-PVFileCategory -safe Windows -folder Root -file $fileName -category ExtraPass1Safe -value $LogonAccountSafe
```

**Comment by mercierv** [comment]
Thank you very much for your answer. I will try that, and on top of that we may install the CCP so it would solve the issue as well. 
Thanks again, I will put this issue as solved  

Cheers, 
V.
